site_name: Hannan Kan
site_url: https://hannankan.github.io/homepage/
repo_name: https://github.com/HannanKan/homepage
theme:
  name: 'material'
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.select
plugins:
  - meta-manager
  - search
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html


nav:
- Home: 'index.md'
- 主页搭建: homepage_build.md
- 书籍:
  - 书单: 'book/books_index.md'
  - 2023年:
    - 技术:
      - 《代码整洁之道》: 'book/代码整洁之道.md'
      - 《架构整洁之道》: 'book/架构整洁之道.md'
- 源码:
  - 技巧总结: 'rfc/源码阅读技巧总结.md'
- 工程实践:
  - 工程实践: 'engineering/工程实践.md'
  - Java/Scala:
    - 并发: 'engineering/java_scala/并发.md'
    - Maven: 'engineering/java_scala/maven.md'
    - 性能优化:
      - 1BRC竞赛: 'engineering/java_scala/性能优化/1brc.md'
      - 1BRC竞赛代码赏析: 'engineering/java_scala/性能优化/1brc-review.md'
      - 线程泄露: 'engineering/java_scala/性能优化/threadLeakInvestigate.md'
  - 快学大数据:
    - 学习大纲: 'engineering/intro2BigDataComponent/outline.md'
    - Hudi:
      - Hudi 简介: 'engineering/intro2BigDataComponent/hudi/hudi_intro.md'
- 优秀博客:
  - 优秀博客汇总: 'blogs/index.md'
- 学习资料:
  - 技术资料: 'technical_materials.md'
  - 人文资料: 'cultural_materials.md'
- 工具推荐:
  - 效率工具: 'utils/efficiency_tools.md'

extra:
  social:
        - icon: fontawesome/solid/envelope
          link: mailto:<hannankan@foxmail.com>
          name: 邮箱地址
        - icon: fontawesome/solid/paper-plane
          link: https://www.zhihu.com/people/HannanKan
          name: 知乎
  search:
    language: 'en, de, ru'
copyright: "Copyright &copy; 2023 - now"

