site_name: Hannan Kan
site_url: https://hannankan.github.io/homepage/
repo_name: https://github.com/HannanKan/homepage
theme:
  name: 'material'
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.select
plugins:
  - meta-manager
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
- Home: 'index.md'
- 主页搭建: homepage_build.md
- 优秀博客:
  - 优秀博客汇总: 'blogs/index.md'
- 书籍:
  - 《代码整洁之道》: 'book/代码整洁之道.md'
  - 《架构整洁之道》: 'book/架构整洁之道.md'
- 源码:
  - 技巧总结: 'rfc/源码阅读技巧总结.md'
- 工程实践:
  - 工程实践: 'engineering/工程实践.md'
extra:
  social:
        - icon: fontawesome/solid/envelope
          link: mailto:<hannankan@foxmail.com>
          name: 邮箱地址
        - icon: fontawesome/solid/paper-plane
          link: https://www.zhihu.com/people/HannanKan
          name: 知乎
  search:
    language: 'en, de, ru'
copyright: "Copyright &copy; 2023 - now"

