site_name: Home Page
site_url: https://hannankan.github.io/homepage/
repo_name: https://github.com/HannanKan/homepage
theme:
  name: 'material'
nav:
- Home: 'index.md'
- About me: about.md
- 主页搭建: homepage_build.md
- 优秀博客:
  - 优秀博客汇总: 'blogs/index.md'
- 书籍:
  - 《代码整洁之道》: 'book/代码整洁之道.md'
  - 《架构整洁之道》: 'book/架构整洁之道.md'
- 源码:
  - 技巧总结: 'rfc/源码阅读技巧总结.md'
- 工程实践:
  - 工程实践: 'engineering/工程实践.md'
extra:
  social:
  search:
    language: 'en, de, ru'
copyright: "Copyright &copy; 2023 - now"

